[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "py3dmol>=2.4.2",
    "rdkit>=2024.9.6",
    "requests>=2.32.3",
    "streamlit>=1.43.2",
    "tqdm>=4.67.1",
]
